default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: blog_app
  pool: 5
  username: admin
  password: imoniavwodo
  host: localhost

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: danicex
  username: danicex
  password: ITQLmOgq2gwLZkvLlIIu3wsueqxtbA2q